services:
  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ../../frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env.local
    command: "npm run dev"
  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
